### ISSUE TITLE
timeFrames color and classes not working

### ISSUE THREAD

**Issue by ansem78** [ldmarz/le-angular-gantt#32]
I am trying to implement timeFrames and dateFrames in my project. The docs say I can set a color or array of CSS classes for a timeFrame. But columns template seems to ignore them. I have checked the HTML in the console and there are no class or ng-class named as the class I set. All columns have only `gantt-column` and `gantt-foreground-col` classes and `ng-class="{'gantt-column-last': $last, 'gantt-column-first': $first}"`. In my controller I have:

<pre>
$scope.timeFrames = {
  day : {
    start : moment('8:00','HH:mm'),
    end : moment('20:00','HH:mm'),
    working : true,
    default : true
  },
  closed : {
    magnet : false,
    working : false,
    classes : ['gantt-closed-timeframe']
  }
};

$scope.dateFrames = {
  holidays : {
    start : moment('2018-07-02','YYYY-MM-DD'),
    end : moment('2018-07-04','YYYY-MM-DD'),
    targets : ['closed']
  },
  weekend : {
    evaluator : function(date) { 
      return [6,7].indexOf(date.isoWeekday())>-1;
    },
    targets : ['closed']
  }
};
</pre>

and in my gantt directive:

`time-frames="timeFrames" date-frames="dateFrames"`

In my CSS:

`.gantt-closed-timeframe {background-color: rgba(100,100,100,0.3);}`

**Comment by ldmarz** [comment]
🤔 this issue maybe you can post in the original repo, because I never use this plugin before 😞
