### ISSUE TITLE
 'gantt.recycler' error 

### ISSUE THREAD

**Issue by OlegMalyutin** [ldmarz/le-angular-gantt#35]
Hi !
Realy good performance on scroll events!  👍 
But in the last version, if just change file  angular-gantt.js from old version angular-gantt to le-angular-gantt angular-gantt.js, and add   'gantt.recycler'  got error : 

Uncaught Error: [$injector:unpr] Unknown provider: $$HashMapProvider <- $$HashMap <- $$animateQueue <- $animate <- $compile <- $mdUtil <- $mdTheming <- $$animateQueue

https://errors.angularjs.org/1.7.7/$injector/unpr?p0=%24%24HashMapProvider%20%3C-%20%24%24HashMap%20%3C-%20%24%24animateQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24mdUtil%20%3C-%20%24mdTheming%20%3C-%20%24%24animateQueue

**Comment by ldmarz** [comment]
hello !! let me learn, You want to use the `gantt.recycler` plugin in your own angular-gantt project?

**Comment by OlegMalyutin** [comment]
I will use just your le-angular-gantt in my applapplication. But can't start. Unfortunately I am newby in angularjs. Can you chage le-angular-gantt code for correct error? Thank you in advance.

**Comment by OlegMalyutin** [comment]
> But in the last version, if just change file angular-gantt.js from old version angular-gantt to le-angular-gantt angular-gantt.js, and add 'gantt.recycler' got error :

Correct version for le-angular-gantt  angular-material: **1.1.5**
Just my mistake sorry.
