### ISSUE TITLE
recycler.collapse(id) and recycler.collapse(id) not working

### ISSUE THREAD

**Issue by OlegMalyutin** [ldmarz/le-angular-gantt#39]
recycler.collapse(id) and recycler.collapse(id) not working

**Comment by ldmarz** [comment]
take a look at this example of my custom API

https://github.com/ldmarz/le-angular-gantt/blob/master/demo.le/demo.controller.ts#L132

**Comment by OlegMalyutin** [comment]
Yes 

>   $scope.collapse = function (id) {
          $scope.api.recycler.collapse(id)
        }


and 
` <button ng-click="collapse(1)"> collapseOne </button>`
No effect. 
But ` <button ng-click="collapseAll()"> collpaseAll </button>`
in same code working.
