### ISSUE TITLE
How to update in guntt.recycler?

### ISSUE THREAD

**Issue by OlegMalyutin** [ldmarz/le-angular-gantt#42]
In tree plugin for update use api.tree.refresh();  but how update  'tree'  in guntt.recycler ?
(for example , if change or set parent in tree hierarchy for task )

**Comment by ldmarz** [comment]
You should always modify the `$scope.data` object because is a two way binding and the gantt should refresh your changes automatically

**Comment by OlegMalyutin** [comment]
I use this simple function for move hierarchy : 
```
 $scope.taskHierarchyRight = function (row) {
        if (row !== undefined) {
          var index = $scope.data.indexOf(row.model);
          if (index > 0) {
            if (row.model.parent !== $scope.data[index - 1].id) {
              row.model.parent = $scope.data[index - 1].id;
            //  $scope.refreshView();
            }
          }
        }
      };
```

it is just set parent id 
but in tree  row is not moving to right whithout this function : 

```
 $scope.refreshView = function () {
        $scope.data.push([]);
        setTimeout(function () {
          $scope.data.splice($scope.data.length - 1, 1);
        }, 1);
}
```

But this function is very bad solution. In result we have flicker and emty css grey row,  which not refreshed

**Comment by OlegMalyutin** [comment]
![default](https://user-images.githubusercontent.com/45938672/53808628-f0cd6d00-3f7c-11e9-9c44-acc86336a620.png)

after call $scope.refreshView
![default](https://user-images.githubusercontent.com/45938672/53808748-3b4ee980-3f7d-11e9-94c4-5568c74af0a9.png)

**Comment by ldmarz** [comment]
try after you nake the changes to force a `$scope.$digest()` to the component that contains your gantt

**Comment by OlegMalyutin** [comment]
Unfortunately  data in function
$scope.$watchCollection('data', function (newData, oldData) 
trigger only  

> $watch() will be triggered by:
> 
> $scope.myArray = [];
> $scope.myArray = null;
> $scope.myArray = someOtherArray;
> 
> $watchCollection() will be triggered by everything above AND:
> 
> $scope.myArray.push({}); // add element
> $scope.myArray.splice(0, 1); // remove element
> $scope.myArray[0] = {}; // assign index to different value
> 
> $watch(..., true) will be triggered by EVERYTHING above AND:
> 
> $scope.myArray[0].someProperty = "someValue";

( https://stackoverflow.com/questions/26535415/angularjs-watch-vs-watchcollection-which-is-better-for-performance )

and $scope.$digest() has no effect
if set $watch(..., true) instead $watchCollection then it is working but we have very expensive functional by performance

**Comment by OlegMalyutin** [comment]
Solution:

```
	$scope.refreshView = function () {

		$scope.api.data.raise.clear();
		$scope.api.data.raise.load($scope.data); 
		$scope.api.groups.refresh(); 
		$scope.api.columns.refresh();	

	}
```
